 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var express = require('express');
var app = express();

app.use('/public', express.static(process.cwd() + '/public'));


app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

// app.route('/new:url')
//     .get(function(req, res){
//       res.send(req.params.url);
// })

app.get('/new/:url*', function(req, res){
  
  var wrongURL = ({error: 'Wrong url format, make sure you have a valid protocol and real site.'});
  var validURL = req.params.url.length == 0 ? res.json(wrongURL) : req.params[0].length == 0 ? res.json(wrongURL): req.params.url + req.params[0];
  
  
  
  res.send(validURL);
})


app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

