 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var express = require('express');
var app = express();

app.use('/public', express.static(process.cwd() + '/public'));


app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

// app.route('/new:url')
//     .get(function(req, res){
//       res.send(req.params.url);
// })

app.get('/new:url', function(req, res))

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

